# Generated by Django 2.2.16 on 2021-08-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=None),
        ),
    ]
