# Generated by Django 2.2.16 on 2021-08-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20210815_1539'),
        ('reviews', '0002_auto_20210814_1845'),
    ]

    operations = [
    ]
